// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   	int numberOfRun= Integer.parseInt(args[0]);
		int greater=0;
		int lessOrEqual=0;
		double ratio=0;

		for (int i=0; i<numberOfRun; i++)
		{
			double randNum= Math.random();
			if (randNum> 0.5)
			{
				greater++;
			}
			else
			{
				lessOrEqual++;
			}
		}

		if (greater>lessOrEqual && lessOrEqual!=0)
		{
			ratio=((double)lessOrEqual)/greater;
		}
		else if (greater <= lessOrEqual && greater!=0)
		{
			ratio=((double)greater)/lessOrEqual;
		}
		System.out.println("> 0.5: " + greater + " times");
		System.out.println("<= 0.5: " + lessOrEqual + " times");
		if (greater!=0 && lessOrEqual!=0) 
		{
		System.out.println("Ratio: "+ ratio);
		}
		 

	}
}
